### ISSUE TITLE
Plateau Finance (PLT)

### ISSUE THREAD

**Issue by PlateauFinance** [traderjoe-xyz/joe-tokenlists#100]
Token Name: Plateau
Token Symbol: PLT
Token Address: 0xeCfE536a209e405Db19887830b366E397f5B917a
![01](https://user-images.githubusercontent.com/91849761/142466030-381b8fde-6356-4e77-9b34-35f2374ef5f0.png)

**Comment by 0xmurloc** [comment]
image is not square, please crop and resize to 200X200 PNG and resubmit.
