### ISSUE TITLE
Add new token

### ISSUE THREAD

**Issue by NAAMToken** [traderjoe-xyz/joe-tokenlists#101]
logo: [https://upload.wikimedia.org/wikipedia/commons/5/54/Naanayam_Token.png](url)

Contact address: https://bscscan.com/token/0xc81ab0514c6ada6e3d55782219d7ca73345edf63

**Comment by 0xmurloc** [comment]
contract invalid

**Comment by NAAMToken** [comment]
Kindly check:
https://bscscan.com/token/0xc81ab0514c6ada6e3d55782219d7ca73345edf63

Please let me know any issue with the contract? its working fine.
