### ISSUE TITLE
Add new token

### ISSUE THREAD

**Issue by OrlaForge** [traderjoe-xyz/joe-tokenlists#102]
0xf6d46849db378ae01d93732585bec2c4480d1f
![FORT](https://user-images.githubusercontent.com/89750895/142563061-fa428c73-9cbd-4f58-9851-50af0a38cc13.png)
d5

**Comment by OrlaForge** [comment]
Fortress FORT

**Comment by Fortress-DAO** [comment]
To be clear, the full token address is:
0xf6d46849db378ae01d93732585bec2c4480d1fd5
(In the original post, the last two characters ("d5") are separated from the rest of the address as the image is inserted in between.)

This is the token of Fortress DAO (https://www.coingecko.com/en/coins/fortress-dao), $FORT.
