### ISSUE TITLE
Add new token

### ISSUE THREAD

**Issue by Will0x** [traderjoe-xyz/joe-tokenlists#104]
O3 Swap Token (O3): 0xEe9801669C6138E84bD50dEB500827b776777d28

Logo:
https://drive.google.com/file/d/1QV1WEm6EaRFIeVqfJH3VUm4gdtIqXYPE/view?usp=sharing

**Comment by 0xmurloc** [comment]
sorry not clicking links pls submit PNG 200X200

**Comment by Will0x** [comment]
> sorry not clicking links pls submit PNG 200X200
![O3](https://user-images.githubusercontent.com/94774292/142768790-a0b57122-47ea-49b8-8b3d-1d2982685000.png)
