### ISSUE TITLE
MiloInu

### ISSUE THREAD

**Issue by alexoura** [traderjoe-xyz/joe-tokenlists#1346]
Name: MiloInu
Symbol: MILO
Contract Address: 0xe98E1DD1541F604e47dB990336f687e9c6FA56D1
Blockchain: Avalanche C-Chain (43114)
Decimals: 18
![logo png](https://github.com/traderjoe-xyz/joe-tokenlists/assets/156849512/03975943-df5a-44f9-a0e8-31003170fc42)

**Comment by alexoura** [comment]
Hello Traderjoe, Please add MILO Token. @Meme

**Comment by Unsehrtain** [comment]
Incorrect, please follow instructions provided. Your token doesn’t currently qualify for tokenlisting
