### ISSUE TITLE
Request Add Logo for xSatoshi token

### ISSUE THREAD

**Issue by xSatoshiFinance** [traderjoe-xyz/joe-tokenlists#20]
Dear Trader JOE Team,
Please help  update our logo on your platform.

+ Our contract : 0x1AdB3ebE3aE7aA4d16b56A8133A14fc3a6ab28A1
+ Our logo : https://xsatoshi.finance/xSatoshiImg/logo.png

xSatoshi Avax  is real meme & dex token with a 100% decentralized community for experiment.

🔹 Website: https://xsatoshi.finance
🔹 Twitter: https://twitter.com/XsatoshiFinance
🔹Telegram Group: @xSatoshiAvax_EN
🔹Telegram Channel: @xSatoshiAvax

Thank
xSatoshi Team

**Comment by 0xmurloc** [comment]
added, closing.
