### ISSUE TITLE
Add Logo

### ISSUE THREAD

**Issue by IMPERIODAO** [traderjoe-xyz/joe-tokenlists#221]
Please add our logo (see attached). 

![imperiodao_logo](https://user-images.githubusercontent.com/96852865/148293790-f5280e18-abe1-4c27-ad28-3a0f88d2bf55.png)

Token URL: https://traderjoexyz.com/?fbclid=IwAR3_BVROkgFI5hJ_yzuYmXglTYbY9yuOPffoC_dGPsjL5HywN3vFrfA4hYc#/trade?inputCurrency=&outputCurrency=0x8eb3aaB271FF81e669d6556E89Ae4911a7cC9788

**Comment by 0xmurloc** [comment]
added
