### ISSUE TITLE
Add token - $POLAR (polarnodes)

### ISSUE THREAD

**Issue by Polar-DANO** [traderjoe-xyz/joe-tokenlists#271]
0x6c1c0319d8ddcb0ffe1a68c5b3829fd361587db4
![favicon](https://user-images.githubusercontent.com/98539943/151518012-4b3ac55c-7aad-4ab8-9598-7133cd469e15.png)
$POLAR (polarnodes)

**Comment by AbeDale** [comment]
The $Polar must be Verified ❄

**Comment by 0xmurloc** [comment]
are u guys able to send PR?

**Comment by Polar-DANO** [comment]
yes we are, what do you need ?

**Comment by Polar-DANO** [comment]
@0xmurloc of course, i just do it
https://github.com/traderjoe-xyz/joe-tokenlists/pull/274
