### ISSUE TITLE
charlie munger token sample

### ISSUE THREAD

**Issue by NephilimDimpu** [traderjoe-xyz/joe-tokenlists#303]
![100656193-Charlie-Munger-gettyp](https://user-images.githubusercontent.com/72041217/153618770-dfd9e0cc-b52c-40c2-b12f-f4b17ecfe39d.jpg)

0x6e84a6216eA6dACC71eE8E6b0a5B7322EEbC0fDd

**Comment by 0xmurloc** [comment]
image must be 200X200 PNG
