### ISSUE TITLE
Add SmartCoin

### ISSUE THREAD

**Issue by jeanclaudevanbammm** [traderjoe-xyz/joe-tokenlists#34]
Thanks Joe Team!

Contract: 0xCC2f1d827b18321254223dF4e84dE399D9Ff116c

Logo: https://raw.githubusercontent.com/jeanclaudevanbammm/joe-tokenlists/add-smartcoin/logos/0xCC2f1d827b18321254223dF4e84dE399D9Ff116c/logo.png

**Comment by 0xmurloc** [comment]
added logo
