### ISSUE TITLE
ADD $SUN LOGO

### ISSUE THREAD

**Issue by Aztecnodes** [traderjoe-xyz/joe-tokenlists#420]
Hi can you add our logo pls? 
ty
![token_200x200](https://user-images.githubusercontent.com/102936246/161655574-9acbe916-4f53-43e1-9088-9dd8384200cb.png)
![token_200x200](https://user-images.githubusercontent.com/102936246/161655604-6a7c1cee-297d-4987-98fa-18a45bb02651.png)
!

**Comment by 0xmurloc** [comment]
pls resubmit logo with contract address.
