### ISSUE TITLE
Please add pAVAX token

### ISSUE THREAD

**Issue by nivra** [traderjoe-xyz/joe-tokenlists#511]
C-chain checksummed address:  0x6ca558bd3eaB53DA1B25aB97916dd14bf6CFEe4E

Token logo 200X200 PNG: 
![pAVAX_logo_200x200](https://user-images.githubusercontent.com/594019/171766106-6ff71615-b4cd-4bdf-a0c5-95adc71e29d2.png)

**Comment by klyed** [comment]
Or just you know.. read the instructions and update it yourself by forking the repo..
