### ISSUE TITLE
Zeus Finance

### ISSUE THREAD

**Issue by Morpheus-Zeus** [traderjoe-xyz/joe-tokenlists#534]
Token contract: 0x4156f18bf7c1ef04248632c66aa119de152d8f2e

Logo:
![200x200 clear bkgd](https://user-images.githubusercontent.com/102832542/180856644-7f49a8f4-6fd8-4378-805c-2d594d53b41d.png)
 
![200x200](https://user-images.githubusercontent.com/102832542/180856708-65c2ad85-94f2-44f6-aa51-9a294a2e2d6f.png)

**Comment by 0xmurloc** [comment]
already added
