### ISSUE TITLE
Zeus Finance

### ISSUE THREAD

**Issue by zeusnode** [traderjoe-xyz/joe-tokenlists#595]
![zeus](https://user-images.githubusercontent.com/99915092/192114168-037f408e-d807-47d3-a785-8dc5125b7ad1.png)
0x8C3633eE619a42d3755327C2524E4d108838c47f

**Comment by zeusnode** [comment]
Name: Zeus Finance
Symbol: ZEUS
Contract: 0x8C3633eE619a42d3755327C2524E4d108838c47f
![zeus](https://user-images.githubusercontent.com/99915092/192114229-eb585656-8f69-45e3-a792-ef46a2e3c22f.png)

Token Image:

**Comment by thejasonnjoe** [comment]
hi, please do a PR if you want to upload the logo, thanks
