### ISSUE TITLE
pumpskin pie PPIE

### ISSUE THREAD

**Issue by pumpskinTeam** [traderjoe-xyz/joe-tokenlists#611]
Name: pumpskin pie
Symbol: PPIE
Contract: 0x325A9463E93aB79bf0302353c99EF70f43f33637
Token Image: 
![PPIE-icon-200-200](https://user-images.githubusercontent.com/100814251/194730412-7bba8ccd-2b71-4f22-b82b-67a5f9ac6a41.png)

**Comment by thejasonnjoe** [comment]
hi, please do a PR if you want to upload the logo, thanks
