### ISSUE TITLE
add ADC(African Development Coin)

### ISSUE THREAD

**Issue by yskore** [traderjoe-xyz/joe-tokenlists#615]
name: ADC (African Development Coin)
symbol: ADC
Address: 0x71e6bb43f1931a2f3c432efb07f83b01a24143a7
![ADC_logo](https://user-images.githubusercontent.com/23510971/195961399-45ace96b-5f52-46df-8526-d6135e4a742e.png)

**Comment by thejasonnjoe** [comment]
hi, please do a pull request if you want to upload the logo, thanks
