### ISSUE TITLE
investclubcoin.com

### ISSUE THREAD

**Issue by RaimundoICC** [traderjoe-xyz/joe-tokenlists#620]
Name: Invest Club Coin
Simbol: ICC
Contract: 0x8c6493c531b89034844bfe73824fb5fe39a8457a
<img width="100" alt="193304394-22bcb068-5e17-4e65-bcf9-3eeebee0bae8" src="https://user-images.githubusercontent.com/114759071/196306253-4b181adf-f752-4955-b85e-5ba11c08dfb2.png">

**Comment by thejasonnjoe** [comment]
please do a PR if you want to upload the logo , thanks
