### ISSUE TITLE
$DCAU Logo Update

### ISSUE THREAD

**Issue by heatengine1** [traderjoe-xyz/joe-tokenlists#668]
Hello JOE Team,

Could you please help us update $DCAU logo?
I appreciate any help you can provide.

Heatengine from Dragon Crypto Gaming
![dcau](https://user-images.githubusercontent.com/110386997/213069224-5a8bf3ad-e87a-4257-9844-15126ebb4b06.png)

**Comment by 0xmurloc** [comment]
@thejasonnjoe can u help

**Comment by thejasonnjoe** [comment]
done
