### ISSUE TITLE
AMiE

### ISSUE THREAD

**Issue by AMiExploration** [traderjoe-xyz/joe-tokenlists#713]
name: AMi Exploration
symbol: AMiE
address: 0xa12eB4d5cB7911E8D471FE708a9f3119fD216a1A
![AMi_200x200](https://user-images.githubusercontent.com/125747446/219871073-158b31db-48a8-4a6b-b827-f1b212929883.png)

**Comment by AMiExploration** [comment]
Hello Team! Is there anything additional we need to do from our side to have this action closed? Thank you very much!

**Comment by 0xmurloc** [comment]
hey pls head to our discord if u need help creating PR, closing for now
