### ISSUE TITLE
IceCubes Logo

### ISSUE THREAD

**Issue by icecubesfinance** [traderjoe-xyz/joe-tokenlists#72]
![icecubes](https://user-images.githubusercontent.com/93214184/139135869-2048fd46-5211-4069-840d-41c9b18b1a1e.png)

ICUBE Contract: 0x951c8a8dee33bd5039a71e7bd4244d5659cf1517

**Comment by 0xmurloc** [comment]
can u use 200X200 PNG log and send PR?

**Comment by icecubesfinance** [comment]
Hi, Here you go!  https://ibb.co/Wvx2jC0 Thanks. From: robotmurlocSent: Tuesday, 2 November 2021 8:51 amTo: traderjoe-xyz/joe-tokenlistsCc: icecubesfinance; AuthorSubject: Re: [traderjoe-xyz/joe-tokenlists] IceCubes Logo (Issue #72) can u use 200X200 PNG log and send PR?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
