### ISSUE TITLE
List token TTM

### ISSUE THREAD

**Issue by pelideachille87** [traderjoe-xyz/joe-tokenlists#792]
"chainId": 43114, 
"address": "0x33342F9fF0c5aB7e6B2c522FF63D365c4d7a58BE", 
"decimals": 18, 
"name": "ToTheMoon", 
"symbol": "TTM", 
"tags": ["DeFi"], 
"logoURI": "[https://user-images.githubusercontent.com/133004052/237089910-284147c1-1543-4942-b8eb-9bac52e59775.png](https://user-images.githubusercontent.com/133004052/237089773-7574ab39-a972-466d-b270-aa1dcdcb837f.png)"

**Comment by thejasonnjoe** [comment]
tokenlist not open for application for now

**Comment by pelideachille87** [comment]
Any news?
