### ISSUE TITLE
$DCAU token logo 

### ISSUE THREAD

**Issue by Heatengine0** [traderjoe-xyz/joe-tokenlists#88]
Dear Trader Joe,

We launched our layer 2 token on 04/11 and transfered liquidity from our layer 1 token - $DREGG
Could you please help us add logo to our token $DCAU and let our users to have a pleasant experience trading on your platform?

Thank you in advance,
Dragon Crypto Gaming team

Token logo is attached below

![dcau](https://user-images.githubusercontent.com/90311164/140500955-b09ca1dd-de74-40bf-a353-719d362c0b48.png)

**Comment by 0xmurloc** [comment]
token address?

**Comment by Heatengine0** [comment]
Oh gosh, I forgot the contract address. Apologies! 

0x100Cc3a819Dd3e8573fD2E46D1E66ee866068f30

Thank you!
