### ISSUE TITLE
Add Onion Coin (ONION)

### ISSUE THREAD

**Issue by farmersonlydefi** [traderjoe-xyz/joe-tokenlists#96]
Logo 300x300: onion.farmersonly.farm/files/logo300.png

C-Chain Address: 0xf6931e67EF0cB20423351A53069719Df2ad76e78

**Comment by 0xmurloc** [comment]
not clicking your links. pls attach regular png here.

**Comment by farmersonlydefi** [comment]
Oh ok, sorry
![logo300](https://user-images.githubusercontent.com/91074469/142383174-5971ed0d-be4b-4d78-80bc-2e78166d7724.png)
