### ISSUE TITLE
Add FarmersOnly Swap Coins (romeFOS, denverFOS, tokyoFOS)

### ISSUE THREAD

**Issue by farmersonlydefi** [traderjoe-xyz/joe-tokenlists#97]
LOGOS 300x300
romeFOS: https://onion.farmersonly.farm/files/rome300.png
denverFOS: https://onion.farmersonly.farm/files/denver300.png
tokyoFOS: https://onion.farmersonly.farm/files/tokyo300.png

AVALANCHE C-CHAIN ADDRESSES
romeFOS: 0xA005B96EF624a6646763715b667343341d590623
denverFOS: 0xb7837aB6000dbdA8683951309c6614Ae279AC62a
tokyoFOS: 0x6514c73189bDc5668B497b6d70C0f69dAce1aDdF

**Comment by 0xmurloc** [comment]
not clicking your links pls attach PNG here

**Comment by farmersonlydefi** [comment]
Ok, sorry, did the same on the other commit :)

denverFOS
![denver300](https://user-images.githubusercontent.com/91074469/142383291-2073997f-ebde-4120-9fb7-c7929f111849.png)

romeFOS
![rome300](https://user-images.githubusercontent.com/91074469/142383297-42388c51-4baa-47a5-8642-1556390e2f42.png)

tokyoFOS
![tokyo300](https://user-images.githubusercontent.com/91074469/142383300-84462e31-35e2-4dba-b7d9-aa426154b051.png)
