### ISSUE TITLE
Please add Akita Inu Token logo 

### ISSUE THREAD

**Issue by cryptoRN** [traderjoe-xyz/joe-tokenlists#98]
Akita Inu : 0xcaF5191fc480F43e4DF80106c7695ECA56E48B18

![akitadog_copy-2](https://user-images.githubusercontent.com/85957278/142081054-443c1621-6785-429d-8928-ed8db7c1be78.png)

**Comment by cryptoRN** [comment]
We know you have a standard of daily volume of which you would consider to whitelist a token. Since we originated on Ethereum and we are newer to Avalanche, our daily volume is most impressive there. 
We have been onboarding our community to Avalanche with the goal to bring liquidty here. We would love it if you would consider whitelisting our token please.

**Comment by cryptoRN** [comment]
I did also notice our WAVAX-AKITA LP address shows all zeros. May I please have you take a look at that for us. 
[
](https://traderjoexyz.com/#/pool/AVAX/0xcaf5191fc480f43e4df80106c7695eca56e48b18)

**Comment by 0xmurloc** [comment]
added logo. pls verify your contract on snowtrace.

**Comment by cryptoRN** [comment]
Hi we verified our contract on Snowtrace! Thank you!
