### ISSUE TITLE
Add NFD (Feisty Doge) to TraderJoe token list 

### ISSUE THREAD

**Issue by WISENWEALTHY** [traderjoe-xyz/joe-tokenlists#99]
contract address: 0xf1293574ee43950e7a8c9f1005ff097a9a713959
token logo: 
![feisty mask](https://user-images.githubusercontent.com/80934108/142289238-bad856da-3a26-44ed-ad95-39a97ee0fbbb.png)

we are going to be adding liquidity within a day. would love to be listed on Trader Joe. this is the first fractionalized cross chain NFT backed coin created by CryptoPathic on twitter. huge community, very involved. I am merely a member of the community, we have been figuring out how to bridge everything pretty much on our own and path sets liquidity everywhere. pls consider listing us. thank you.

**Comment by 0xmurloc** [comment]
added logo
token list for tokens that trade top 30 in daily volume

**Comment by WISENWEALTHY** [comment]
nice. thank you, murloc
